# Site settings
title: "Sara Rampazzi"
description: "Sara Rampazzi resume"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Sara Rampazzi"
resume_title:                   "Computer Science Research Affiliate"
resume_contact_email:           "srampazz@umich.edu"
resume_contact_telephone:       "+1 (734)8810610"
#resume_contact_address:         "742 Evergreen Terrace, Springfield"
resume_header_contact_info: "<p><img src='images/ph.png' alt='tel' class='icon-link' align='top'> +1 (734) 8810610 &emsp; &emsp; <img src='images/ml.png' alt='mail' class='icon-link' align='top'> srampazz@umich.edu </p> "
resume_header_intro: "<p>I'm a Computer Science Engineer working on embedded system security with professor <a href='https://web.eecs.umich.edu/~kevinfu/'>Kevin Fu</a> at <a href='https://www.cse.umich.edu/'>Michigan University</a> - <a href='https://spqr.eecs.umich.edu/'>SPQR laboratory</a>.</p><p> Basically I run models, write software and hack hardware to make cool stuff.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
# resume_looking_for_work:        "no"

# Decide which sections to use
# comment out to hide
resume_section_projects:        true
resume_section_experience:      true
resume_section_education:       true
# resume_section_skills:          true
# resume_section_recognition:     true
resume_section_links:           true
# resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/SaraRampazzi"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/sara-rampazzi-1054407b/"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://sararampazzi.com"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
